name: CI/CD PHP Deploy VP

on:
  push:
    branches:
      - master

jobs:
  ssh-test:
    runs-on: ubuntu-latest

    steps:
      - name: Executing remote SSH commands for PHP Docker app
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            echo "Conexión exitosa al servidor"

            cd ${{ secrets.WORK_DIR }}
            echo "📥 Actualizando repositorio..."
            git fetch origin ${{ secrets.MAIN_BRANCH }}
            git checkout ${{ secrets.MAIN_BRANCH }}
            git pull origin ${{ secrets.MAIN_BRANCH }}

            echo "🚀 Construyendo y levantando contenedores..."

            docker compose up -d --build
            
            echo "⏳ Esperando unos segundos a que la base de datos esté lista..."
            sleep 5

            echo "🗄️ Ejecutando migraciones de Laravel..."
            docker compose exec -T app_inmobiliaria php artisan migrate --force

            echo "🧹 Optimizando la aplicación (Caché)..."
            
            docker compose exec -T app_inmobiliaria php artisan config:cache
            docker compose exec -T app_inmobiliaria php artisan route:cache
            docker compose exec -T app_inmobiliaria php artisan view:cache

            echo "✅ ¡Despliegue completado con éxito en $HOSTNAME!"